## Plot the 30-day mortality rates for heart attack, nothing to submit though ...
## Originally read csv file in character ...
outcome <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
head(outcome)

## numerize one data column and histogram it ...
outcome[, 11] <- as.numeric(outcome[, 11])
hist(outcome[, 11])
